# Generated by Django 4.1.5 on 2023-01-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='cargo_weight',
            field=models.IntegerField(default=0),
        ),
    ]
